# name: WordPress CI/CD

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build-deploy:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v2

#     # - name: Create 
#     #   run: |
#     #     sudo apt-get update && sudo apt-get install openssh-client -y
#     #     mkdir -p ~/.ssh/
#     #     echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
#     #     chmod 600 ~/.ssh/id_rsa

#     - name: Setup SSH
#       uses: shimataro/ssh-key-action@v2
#       with:
#           key: ${{ secrets.SSH_PRIVATE_KEY }}
#           name: id_rsa
#           known_hosts: ${{ secrets.KNOWN_HOSTS }}
        

#     - name: Deploy on EC2
#       run: |
#          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@3.86.224.206 'cd /var/www/html/wordpress && git pull'
          